### ISSUE TITLE
Way to dynamiccally add waves on already mounted component?

### ISSUE THREAD

**Issue by wmonecke** [gVguy/svg-waves#1]
Is there a way I could add another wave on an already mounted wave component?

Also, thank you for this amazing library :)

**Comment by gVguy** [comment]
Short answer: no.

Long answer: Individual waves are generated when waves constructor is called based on fills count and other properties (some of which are randomized for each individual wave). Theoretically, you could manually call a wave constructor from `wave.js`, manually passing all the required properties. Then add the returned wave instance to `waves` array on the main instance, and then manually append your newly created wave's `svgEl` to main instance's svg stored in its `mounted` property. But as you can see it would involve a lot of hacking. So you probably shouldn't do it.

Instead, consider creating a fresh instance with an increased number of waves and mounting it again to the same container.
